databases:
  - name: expense_calculator_db
    databaseName: expense_calculator_db
    user: expense_calculator
    region: singapore

services:
  - type: web
    name: expense_calculator
    env: ruby
    region: singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: expense_calculator_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
