databases:
  - name: expense-calculator-db
    databaseName: expense-calculator-db
    user: expense-calculator
    region: singapore

services:
  - type: web
    name: expense-calculator
    env: ruby
    regin: singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: expense-calculator-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
